name: CI-CD - build

on:
   push:
     branches:
       - main
      pull_request:
         branches:
           - main
jobs:
    build:
      name: Build project
        runs-on: ubuntu-latest
      
  steps: 
    - name: checkout do repositorio
      uses: actions/checkout@v4

    - name: configuração java 21 
      uses: actions/setup-java@v4
      with: 
        java-version: '21'
        distribution: 'temurin'
        cache: maven

      - name: build da aplicação
        run: mvn clean package -DskipTest

      - name: Salvar
          uses:action/upload-artifact@v4
          with:
            name: app-war
            path:  target/*.war
            retention-day: 7
